from django.db import models

# Create your models here.

class Student(models.Model):
    idNumber = models.CharField(max_length=15)
    result = models.IntegerField()
    CC100 = models.FloatField()
    CC101 = models.FloatField()
    CC102 = models.FloatField()
    CC103 = models.FloatField()
    CC104 = models.FloatField()
    CC105 = models.FloatField()
    CS111 = models.FloatField()
    CS120 = models.FloatField()
    CS121 = models.FloatField()
    CS122 = models.FloatField()
    CS123 = models.FloatField()
    CS124 = models.FloatField()
    CS125 = models.FloatField()
    CS126 = models.FloatField()
    CS127 = models.FloatField()
    CS130 = models.FloatField()
    CS131 = models.FloatField()
    CS132 = models.FloatField()
    CS134 = models.FloatField()
    CS135 = models.FloatField()
    CS136 = models.FloatField()
    CS137 = models.FloatField()
    IT112 = models.FloatField()
    IT114 = models.FloatField()
    IT121 = models.FloatField()
    IT122 = models.FloatField()
    IT123 = models.FloatField()
    IT124 = models.FloatField()
    IT125 = models.FloatField()
    IT126 = models.FloatField()
    IT131 = models.FloatField()
    IT132 = models.FloatField()
    IT133 = models.FloatField()
    IT134 = models.FloatField()
    IT135 = models.FloatField()
    IT136 = models.FloatField()
    IT137 = models.FloatField()
    IT144 = models.FloatField()
    MATH103 = models.FloatField()
    MATH104 = models.FloatField()